### ISSUE TITLE
forge compatability? 

### ISSUE THREAD

**Issue by Hugs288** [light-and-ray/sd-webui-lama-cleaner-masked-content#2]
great extension i like it a lot but it doesnt work with forge because of different controlnet integrations
https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by light-and-ray** [comment]
Yes, it should be rewritten almost from scratch too because forge has very different internal code 

https://github.com/light-and-ray/sd-webui-cn-in-extras-tab/issues/2

**Comment by ghost** [comment]
so it wont happen? if so thats unfortunate

**Comment by light-and-ray** [comment]
I think I will, but later

**Comment by light-and-ray** [comment]
Implemented: https://github.com/light-and-ray/sd-webui-lama-cleaner-masked-content/commit/24bcf0c84f51329eee7a6f5749ca3de9d96c4618
