### ISSUE TITLE
Request API support

### ISSUE THREAD

**Issue by qwe2691037** [light-and-ray/sd-webui-lama-cleaner-masked-content#3]
The webui effect is great, I hope it can support APIs
![image](https://github.com/light-and-ray/sd-webui-lama-cleaner-masked-content/assets/13066182/10a3f576-2a75-4d8c-9149-58e1ebc9bad5)

![image](https://github.com/light-and-ray/sd-webui-lama-cleaner-masked-content/assets/13066182/620debec-251e-4984-be70-21384100a31a)

![image](https://github.com/light-and-ray/sd-webui-lama-cleaner-masked-content/assets/13066182/f95eb29c-cf6d-42a3-a1de-a846a5d12065)

**Comment by light-and-ray** [comment]
It supports api, why not. Just choose masked content 4

**Comment by sunhui0608** [comment]
> It supports api, why not. Just choose masked content 4

May I know to "choose masked content 4"?

**Comment by light-and-ray** [comment]
> > It supports api, why not. Just choose masked content 4
> 
> May I know to "choose masked content 4"?

most likely but I'm not 100% sure

`"inpainting_fill": 4`
