### ISSUE TITLE
OSError: cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by thejohnd0e** [light-and-ray/sd-webui-lama-cleaner-masked-content#4]
![Screenshot - 2024-03-03 13 04 53](https://github.com/light-and-ray/sd-webui-lama-cleaner-masked-content/assets/115493464/05c1de53-5925-41f9-844d-e882e921272e)

**Comment by light-and-ray** [comment]
Set in the settings "Live preview file format" to png or webp. I'll make a PR to sd-webui to avoid the problem in future sd-webui versions

**Comment by light-and-ray** [comment]
Thanks for reporting 👍🏻

**Comment by thejohnd0e** [comment]
> Set in the settings "Live preview file format" to png or webp. I'll make a PR to sd-webui to avoid the problem in future sd-webui versions

Yes, I did. It works great now. Thanks!
